### ISSUE TITLE
Please remove glow

### ISSUE THREAD

**Issue by BieHDC** [minecraftchest1/IRCgen2-Specs#1]
thanks

**Comment by minecraftchest1** [comment]
Please explain more. What do you mean by glow?

**Comment by BieHDC** [comment]
replace this glow `IRCg2 @Target=1 @messageID=1 @from=Minecraftchest1 message="(This is an example message.)" /endmsg/` with `do a size header of type uint64_t at the beginning(size of header and body), version of sz 32 at next pos, then do another type of 32 which specifies the type of the message, followed by the body`

**Comment by minecraftchest1** [comment]
https://github.com/minecraftchest1/IRCgen2-Specs/pull/2
Will try.

**Comment by minecraftchest1** [comment]
Something like this?
```
IRCg2 @meta="(size=uint64_t messagetype=32)" Target=1 @messageID=1 @from=Minecraftchest1 message="(This is an example message.)" /endmsg/
```

**Comment by minecraftchest1** [comment]
Closing.
